<a href="https://colab.research.google.com/github/Mark12481632/Python-Language/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [47]:
# Set display params for Pandas' output:
# Set the display width to a larger value (e.g., 150 characters)
pd.set_option('display.width', 170)

# Set the maximum number of columns to be displayed (No limit)
pd.set_option('display.max_columns', None)

# Set the maximum number of rows to be displayed (10)
pd.set_option('display.max_rows', 10)

# Set the display options
pd.set_option('display.max_rows', 10)
pd.set_option('display.min_rows', 10)

**Loading and displaying data from CSV file.**

In [51]:
# Load the Google Play Store Apps dataset
url = "https://raw.githubusercontent.com/Mark12481632/Python-Language/main/melb_data.csv"

df = pd.read_csv(url)

# Display the first few 6 rows of the dataset
print(df.head(6))

print("===============================================")

# Display last 4 rows of dataset
print(df.tail(4))

       Suburb           Address  Rooms Type      Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin  3/12/2016       2.5    3067.0       2.0       1.0  1.0     202.0           NaN        NaN
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin  4/02/2016       2.5    3067.0       2.0       1.0  0.0     156.0          79.0     1900.0
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin  4/03/2017       2.5    3067.0       3.0       2.0  0.0     134.0         150.0     1900.0
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin  4/03/2017       2.5    3067.0       3.0       2.0  1.0      94.0           NaN        NaN
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson  4/06/2016       2.5    3067.0       3.0       1.0  2.0     120.0         142.0     2014.0
5  Abbotsford    129 Charles St      2    h   941000.0      S  Jellis  7/05/2016       2.5    3067.0       2.0       1.0  0.0     181.0           NaN        NaN

  CouncilArea  Lattitude  Longtitude             Regionname  Propertycount
0       Yarra   -37.7996    144.9984  Northern Metropolitan         4019.0
1       Yarra   -37.8079    144.9934  Northern Metropolitan         4019.0
2       Yarra   -37.8093    144.9944  Northern Metropolitan         4019.0
3       Yarra   -37.7969    144.9969  Northern Metropolitan         4019.0
4       Yarra   -37.8072    144.9941  Northern Metropolitan         4019.0
5       Yarra   -37.8041    144.9953  Northern Metropolitan         4019.0
===============================================
             Suburb        Address  Rooms Type      Price Method   SellerG        Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt  \
13576  Williamstown  77 Merrett Dr      3    h  1031000.0     SP  Williams  26/08/2017       6.8    3016.0       3.0       2.0  2.0     333.0         133.0     1995.0
13577  Williamstown    83 Power St      3    h  1170000.0      S     Raine  26/08/2017       6.8    3016.0       3.0       2.0  4.0     436.0           NaN     1997.0
13578  Williamstown   96 Verdon St      4    h  2500000.0     PI   Sweeney  26/08/2017       6.8    3016.0       4.0       1.0  5.0     866.0         157.0     1920.0
13579    Yarraville     6 Agnes St      4    h  1285000.0     SP   Village  26/08/2017       6.3    3013.0       4.0       1.0  1.0     362.0         112.0     1920.0

      CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
13576         NaN  -37.85927   144.87904  Western Metropolitan         6380.0
13577         NaN  -37.85274   144.88738  Western Metropolitan         6380.0
13578         NaN  -37.85908   144.89299  Western Metropolitan         6380.0
13579         NaN  -37.81188   144.88449  Western Metropolitan         6543.0

In [45]:
# Show some statistics on the CSV data:
print("Shape:", df.shape)
print("Columns:", df.columns)

# Summary information on CSV data.
df.info()

Shape: (13580, 21)
Columns: Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'CouncilArea', 'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [48]:
# Another way to display part of the dataframe is:

df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

**Next Steps**